### ISSUE TITLE
Create Screen for user that has already accepted invitation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web-vue-OLD#100]
Users that try to accept the invitation more then once are seeing a network error screen. Please create the below screen for users that try to accept the invitation more then once and decline the invitation after it has already been accepted 

![Invitation already accepted .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2e184a4b-acea-494b-bac8-6acc8568f20e)

**Comment by sergeysemenuta** [comment]
Users that try to accept the invitation more than once are seeing a network error screen.
https://www.screencast.com/t/iZvxotGZbHyx
Checked on:
https://web-staging.mindlogger.org/

**Comment by sergeysemenuta** [comment]
Testing is blocked by [36](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/36)

**Comment by sergeysemenuta** [comment]
Add quotation marks to the applet name because it is not clear where the applet name is. The dot is missing at the end.
![2021-01-22_17-01-12.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ab68a748-a896-47ae-babc-e0b7cc5e9a96)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by sergeysemenuta** [comment]
The asterisk has been added to the applet name. I mentioned in the comment above that quotation marks  should be added to the applet name
![2021-01-28_10-38-52.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/aa0288db-6db6-4c05-b713-44e625862fe8)

**Comment by sergeysemenuta** [comment]
Verified on:
https://web-staging.mindlogger.org/
Win 10 // Chrome 88
![2021-01-29_8-18-24.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/05d64b41-07b4-4f9c-848e-1ff7e90c7558)
