### ISSUE TITLE
I want to select the language for the invitation to a new user

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web-vue-OLD#83]
As a coordinator, I want to select the language that the invitation is sent to the user in so that they can read it in their own native language 

Requirements 
* [Content](https://docs.google.com/spreadsheets/d/1XLI0t3heBJ366I36D8pUbHLz8xWV4Um-l965sa5G6PU/edit?usp=sharing)
*Give the coordinator the ability to select the invitation language before sending one to a new user 
* French is the required language
* Future support for other languages should be easily done after this has been setup (generic names for all the text strings in the code, and translation resource files)
* English is default 

Acceptance Criteria
Given I am a coordinator
When I send a new invitation
Then I select a language to send the invitation in 

Given I am a user
When I receive an invitation email 
Then it is delivered in my local language of French

**Comment by sergeysemenuta** [comment]
Works as expected regarding the requirements.
https://admin-staging.mindlogger.org
Win 10 // Chome  86 // Firefox 82
