### ISSUE TITLE
I want to accept an invitation in my local language 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web-vue-OLD#84]
As a user, I want to accept or decline my invitation in my local language so that I can understand what I am agreeing to. 

Requirements 
[Content](https://docs.google.com/spreadsheets/d/1XLI0t3heBJ366I36D8pUbHLz8xWV4Um-l965sa5G6PU/edit?usp=sharing)
Based in the language of the invitation email, when the user wants to accept the invitation then the website is translated in the same language 
French is the required language
Future support for other languages should be easily done after this has been setup (generic names for all the text strings in the code, and translation resource files)

Acceptance Criteria
Given I am a user 
When I intiate the process to join MindLogger 
Then the website to create an account accept the invitation is in the same language as the email

**Comment by sergeysemenuta** [comment]
Works as expected. The user is able to accept or decline the invitation in the local language
https://www.screencast.com/t/bGlpLubv
