### ISSUE TITLE
As a user, you shouldn't be able to see invitations for other users

### ISSUE THREAD

**Issue by ngonzalvez** [ChildMindInstitute/mindlogger-web-vue-OLD#85]
When logged in as a user, you are able to accept invitations for other users if you have the link. Furthermore, if you accept the invitation, the resulting profile is a mix of both users data.

**Expected result:**
As a user, you shouldn't be able to see invitations for other users, even if you have the invitation link.

**Proposed implementation:**
In the back-end, check that current user and the user in the invitation match before sending the data to the front-end.

![image](https://user-images.githubusercontent.com/1501339/94994174-5ffdaf80-056c-11eb-890f-3c7fc66d70f0.png)

**Comment by WorldImpex** [comment]
This is an expected feature
