### ISSUE TITLE
Accepting an ML Invitation should open the French Version of ML

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-web-vue-OLD#87]
Steps to recreate: 
1. Receive an invitation for an applet in French and click accept/ decline 
2. A new tab opens with ML web
3. See results

Expected: The website is loaded in French 
Actual: Website is loaded in English 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/135112ea-c23d-424b-b527-45e8c80fd5c9)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/55d49788-136d-4443-bb41-3ed91d6e5479)

**Comment by sergeysemenuta** [comment]
Works as expected.
https://www.screencast.com/t/uwQB7cu8MZ
Win 10 Chrome 86
